# Generated by Django 5.2.6 on 2025-11-21 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('id_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('dni_ent', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
            ],
            options={
                'db_table': 'entrenador',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('dni_resp', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'responsable',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=30, unique=True)),
                ('rol', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_esc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_esc', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('solicitud_enviada', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escuela',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('tipo', models.CharField(default='nota_secretario', max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_esc', models.ForeignKey(db_column='id_esc', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.escuela')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('pk', models.CompositePrimaryKey('dni_alumno', 'id_esc', blank=True, editable=False, primary_key=True, serialize=False)),
                ('dni_alumno', models.ForeignKey(db_column='dni_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.alumno')),
                ('id_esc', models.ForeignKey(db_column='id_esc', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.escuela')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('pk', models.CompositePrimaryKey('dni_ent', 'id_capacitacion', blank=True, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_participacion', models.DateField(blank=True, null=True)),
                ('dni_ent', models.ForeignKey(db_column='dni_ent', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.entrenador')),
                ('id_capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.capacitacion')),
            ],
            options={
                'db_table': 'participacion',
            },
        ),
        migrations.AddField(
            model_name='entrenador',
            name='periodo',
            field=models.ForeignKey(blank=True, db_column='periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.periodo'),
        ),
        migrations.CreateModel(
            name='EntDiscEscPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina', models.ForeignKey(blank=True, db_column='id_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.disciplina')),
                ('dni_ent', models.ForeignKey(blank=True, db_column='dni_ent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.entrenador')),
                ('id_esc', models.ForeignKey(blank=True, db_column='id_esc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.escuela')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.periodo')),
            ],
            options={
                'db_table': 'ent_disc_esc_per',
            },
        ),
        migrations.CreateModel(
            name='AluDiscEscPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_alumno', models.ForeignKey(blank=True, db_column='dni_alumno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.alumno')),
                ('id_disciplina', models.ForeignKey(blank=True, db_column='id_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.disciplina')),
                ('id_esc', models.ForeignKey(blank=True, db_column='id_esc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.escuela')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.periodo')),
            ],
            options={
                'db_table': 'alu_disc_esc_per',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('id_esc', models.ForeignKey(db_column='id_esc', on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.escuela')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni_tutor',
            field=models.ForeignKey(blank=True, db_column='dni_tutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.tutor'),
        ),
    ]
