# Generated by Django 5.2.6 on 2025-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('nota_secretario', 'Nota al Secretario'), ('respaldo_institucional', 'Respaldo Institucional')], max_length=50),
        ),
    ]
