# Generated by Django 5.2.6 on 2025-11-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_remove_periodo_periodo_periodo_id_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='dni_resp',
            field=models.ForeignKey(blank=True, db_column='dni_resp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.responsable'),
        ),
    ]
