# Generated by Django 5.2.6 on 2025-11-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_escuela_dni_resp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='id_periodo',
            new_name='periodo',
        ),
    ]
