# Generated by Django 5.2.6 on 2025-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0004_rename_id_periodo_periodo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
