# Generated by Django 5.2.6 on 2025-11-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0005_escuela_latitud_escuela_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='buena_conducta',
            field=models.FileField(blank=True, null=True, upload_to='entrenadores/conducta/'),
        ),
    ]
